db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/storage
db.user=operator
db.pass=1

sql.create=db/create.sql
sql.init=db/init.sql
sql.delete=db/delete.sql
sql.show=db/show.sql

jdbc.jar=lib/postgresql-42.7.3.jar
out.dir=out
out.dump=out/dump.txt